/**
 * JWT Token Verification (against .NET Backend tokens)
 *
 * Tokens are generated by the .NET Backend. This utility only verifies them.
 */

import jwt from 'jsonwebtoken';

/** Shape of claims inside .NET Backend's access token */
export interface DotNetJwtPayload {
  /** http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier */
  'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier'?: string;
  sub?: string;
  /** http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress */
  'http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'?: string;
  /** http://schemas.microsoft.com/ws/2008/06/identity/claims/role */
  'http://schemas.microsoft.com/ws/2008/06/identity/claims/role'?: string;
  nameid?: string;
  tenantId?: string;
  iat?: number;
  exp?: number;
}

/** Normalized user info extracted from a valid .NET JWT */
export interface VerifiedUser {
  userId: number;
  email: string;
  role: string;
  tenantId: number;
}

let secret = '';
let issuer = '';
let audience = '';

export class JwtUtil {
  static initialize(config: { secret: string; issuer: string; audience: string }): void {
    secret = config.secret;
    issuer = config.issuer;
    audience = config.audience;
  }

  /**
   * Verify a .NET Backend access token and return normalized user info.
   * Throws on invalid/expired tokens.
   */
  static verifyAccessToken(token: string): VerifiedUser {
    if (!secret) {
      throw new Error('JwtUtil not initialized. Call initialize(config) first.');
    }

    const decoded = jwt.verify(token, secret, {
      algorithms: ['HS256'],
      issuer,
      audience,
    }) as DotNetJwtPayload;

    const userId = Number(
      decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier'] || decoded.nameid || decoded.sub
    );
    const email = decoded['http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress'] || '';
    const role = decoded['http://schemas.microsoft.com/ws/2008/06/identity/claims/role'] || '';
    const tenantId = Number(decoded.tenantId || 0);

    if (!userId || !email) {
      throw new Error('Token missing required claims (userId, email)');
    }

    return { userId, email, role, tenantId };
  }

  /**
   * Decode token without verification (use with caution)
   */
  static decodeToken<T = any>(token: string): T | null {
    try {
      return jwt.decode(token) as T;
    } catch {
      return null;
    }
  }

  /**
   * Check if token is expired (without verifying signature)
   */
  static isTokenExpired(token: string): boolean {
    try {
      const decoded = jwt.decode(token) as any;
      if (!decoded || !decoded.exp) return true;
      return decoded.exp * 1000 < Date.now();
    } catch {
      return true;
    }
  }

  /**
   * Extract token from Bearer header
   */
  static extractTokenFromHeader(authHeader?: string): string | null {
    if (!authHeader) return null;
    const [scheme, token] = authHeader.split(' ');
    if (scheme?.toLowerCase() !== 'bearer') return null;
    return token || null;
  }
}
