/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessage } from './chat-message';
import { ChatParticipant } from './chat-participant';
import { ConversationStatus } from './conversation-status';
import { ConversationType } from './conversation-type';


export interface ChatConversation { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    conversationId?: number;
    profileId1?: number;
    profileId2?: number;
    userId1?: number;
    userId2?: number;
    tenantId?: number;
    conversationName?: string | null;
    type?: ConversationType;
    status?: ConversationStatus;
    lastMessageDate?: string | null;
    lastMessageId?: number | null;
    lastMessagePreview?: string | null;
    isArchived?: boolean;
    isBlocked?: boolean;
    blockedByUserId?: number | null;
    blockedDate?: string | null;
    blockReason?: string | null;
    totalMessagesCount?: number;
    unreadMessagesCount1?: number;
    unreadMessagesCount2?: number;
    rowVersion?: string | null;
    messages?: Array<ChatMessage> | null;
    participants?: Array<ChatParticipant> | null;
    lastMessage?: ChatMessage;
}
export namespace ChatConversation {
}


