/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ParticipantStatus } from './participant-status';
import { ChatConversation } from './chat-conversation';
import { ParticipantRole } from './participant-role';


export interface ChatParticipant { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    participantId?: number;
    conversationId?: number;
    profileId?: number;
    userId?: number;
    tenantId?: number;
    role?: ParticipantRole;
    status?: ParticipantStatus;
    joinedDate?: string;
    leftDate?: string | null;
    lastSeenDate?: string | null;
    isOnline?: boolean;
    receiveNotifications?: boolean;
    isTyping?: boolean;
    typingStarted?: string | null;
    displayName?: string | null;
    profilePhotoUrl?: string | null;
    rowVersion?: string | null;
    conversation?: ChatConversation;
}
export namespace ChatParticipant {
}


