/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentType } from './attachment-type';
import { ChatMessage } from './chat-message';


export interface ChatAttachment { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    messageId?: string;
    conversationId?: string;
    uploadedByUserId?: string;
    tenantId?: string;
    fileName?: string | null;
    originalFileName?: string | null;
    filePath?: string | null;
    fileUrl?: string | null;
    contentType?: string | null;
    fileSize?: number;
    type?: AttachmentType;
    thumbnailUrl?: string | null;
    width?: number | null;
    height?: number | null;
    duration?: number | null;
    isProcessed?: boolean;
    processingStatus?: string | null;
    uploadedDate?: string;
    expiryDate?: string | null;
    message?: ChatMessage;
}
export namespace ChatAttachment {
}


