/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageStatus } from './message-status';
import { MessageReadStatus } from './message-read-status';
import { ChatConversation } from './chat-conversation';
import { ChatAttachment } from './chat-attachment';
import { MessageType } from './message-type';


export interface ChatMessage { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    messageId?: number;
    conversationId?: number;
    senderProfileId?: number;
    senderUserId?: number;
    tenantId?: number;
    content?: string | null;
    type?: MessageType;
    status?: MessageStatus;
    sentDate?: string;
    deliveredDate?: string | null;
    readDate?: string | null;
    editedDate?: string | null;
    isEdited?: boolean;
    deletedDate?: string | null;
    deletedByUserId?: number | null;
    replyToMessageId?: number | null;
    metadata?: string | null;
    isEncrypted?: boolean;
    encryptionKey?: string | null;
    rowVersion?: string | null;
    conversation?: ChatConversation;
    replyToMessage?: ChatMessage;
    replies?: Array<ChatMessage> | null;
    attachments?: Array<ChatAttachment> | null;
    readStatuses?: Array<MessageReadStatus> | null;
}
export namespace ChatMessage {
}


