/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ChatMessage } from './chat-message';


export interface MessageReadStatus { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    readStatusId?: number;
    messageId?: number;
    conversationId?: number;
    profileId?: number;
    userId?: number;
    tenantId?: number;
    isRead?: boolean;
    readDate?: string | null;
    isDelivered?: boolean;
    deliveredDate?: string | null;
    rowVersion?: string | null;
    message?: ChatMessage;
}

