/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface CareerDetails { 
    profileId?: number;
    tenantId?: number;
    educationArea?: string | null;
    education?: string | null;
    occupationType?: string | null;
    occupationDetails?: string | null;
    workingCityCountry?: string | null;
    incomeAmount?: number | null;
    incomePeriod?: string | null;
    createdAt?: string;
    updatedAt?: string;
    profile?: UserProfile;
}

