/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface ContactDetails { 
    profileId?: number;
    tenantId?: number;
    idProofNumber?: string | null;
    residenceAddress?: string | null;
    contactEmail?: string | null;
    createdAt?: string;
    updatedAt?: string;
    profile?: UserProfile;
}

