/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface FamilyDetails { 
    profileId?: number;
    tenantId?: number;
    fatherStatus?: boolean | null;
    motherStatus?: boolean | null;
    brothers?: number;
    marriedBrothers?: number;
    sisters?: number;
    marriedSisters?: number;
    parentsFullName?: string | null;
    parentsOccupation?: string | null;
    parentsResidentCity?: string | null;
    familyWealth?: string | null;
    mamaSurnamePlace?: string | null;
    nativeDistrict?: string | null;
    nativeTaluka?: string | null;
    intercastMarriage?: boolean | null;
    intercastRelation?: string | null;
    createdAt?: string;
    updatedAt?: string;
    profile?: UserProfile;
}

