/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface PartnerPreference { 
    profileId?: number;
    expectedManglik?: boolean | null;
    expectedCaste?: string | null;
    maxAgeDifference?: number | null;
    expectedHeightFt?: number | null;
    expectedHeightIn?: number | null;
    expectedEducation?: string | null;
    expectedOccupationIncome?: string | null;
    divorcee?: boolean | null;
    createdAt?: string;
    updatedAt?: string;
    profile?: UserProfile;
}

