/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface PersonalDetails { 
    profileId?: number;
    tenantId?: number;
    firstName?: string | null;
    middleName?: string | null;
    lastName?: string | null;
    dobDay?: number;
    dobMonth?: string | null;
    dobYear?: number;
    gender?: string | null;
    religion?: string | null;
    caste?: string | null;
    subCaste?: string | null;
    maritalStatus?: string | null;
    heightFt?: number | null;
    heightIn?: number | null;
    weightKg?: number | null;
    bloodGroup?: string | null;
    complexion?: string | null;
    physicalDisability?: boolean;
    disabilityDetail?: string | null;
    diet?: string | null;
    spectacles?: boolean | null;
    lens?: boolean | null;
    personality?: string | null;
    dateOfBirth?: string | null;
    createdAt?: string;
    updatedAt?: string;
    profile?: UserProfile;
}

