/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfilePhotoDto { 
    photoId?: number;
    photoUrl?: string | null;
    isProfilePicture?: boolean;
    uploadedAt?: string;
}

