/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProfile } from './user-profile';


export interface ProfilePhoto { 
    photoId?: number;
    profileId?: number;
    photoSlot?: number;
    fileName?: string | null;
    fileUrl?: string | null;
    isPrimary?: boolean;
    createdAt?: string;
    profile?: UserProfile;
}

