/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PublicProfileDto { 
    profileId?: number;
    displayName?: string | null;
    age?: number | null;
    city?: string | null;
    religion?: string | null;
    caste?: string | null;
    profilePicture?: string | null;
    bio?: string | null;
    isVerified?: boolean;
}

