/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ContactDetails } from './contact-details';
import { CareerDetails } from './career-details';
import { PartnerPreference } from './partner-preference';
import { PersonalDetails } from './personal-details';
import { ProfilePhoto } from './profile-photo';
import { FamilyDetails } from './family-details';


export interface UserProfile { 
    profileId?: number;
    userId?: number;
    tenantId?: number;
    profileCode?: string | null;
    fullName?: string | null;
    age?: number | null;
    bio?: string | null;
    locationText?: string | null;
    occupationText?: string | null;
    isDeleted?: boolean;
    isVerified?: boolean;
    profileCompletionPercent?: number;
    lastActiveAt?: string | null;
    searchScore?: number | null;
    createdAt?: string;
    updatedAt?: string;
    personalDetails?: PersonalDetails;
    familyDetails?: FamilyDetails;
    careerDetails?: CareerDetails;
    contactDetails?: ContactDetails;
    partnerPreference?: PartnerPreference;
    profilePhotos?: Array<ProfilePhoto> | null;
}

