/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Users/by-tenant/{tenantId}
     * @param tenantId 
     */
    apiUsersByTenantTenantIdGet(tenantId: number, extraHttpRequestParams?: any): Observable<Array<User>>;

    /**
     * 
     * 
     * @endpoint delete /api/Users/{id}
     * @param id 
     */
    apiUsersIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/Users/{id}
     * @param id 
     */
    apiUsersIdGet(id: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @endpoint put /api/Users/{id}
     * @param id 
     * @param user 
     */
    apiUsersIdPut(id: number, user?: User, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/Users
     * @param user 
     */
    apiUsersPost(user?: User, extraHttpRequestParams?: any): Observable<{}>;

}
