/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { SubscriptionPlan } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SubscriptionPlansServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/SubscriptionPlans
     */
    apiSubscriptionPlansGet(extraHttpRequestParams?: any): Observable<Array<SubscriptionPlan>>;

    /**
     * 
     * 
     * @endpoint delete /api/SubscriptionPlans/{id}
     * @param id 
     */
    apiSubscriptionPlansIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/SubscriptionPlans/{id}
     * @param id 
     */
    apiSubscriptionPlansIdGet(id: number, extraHttpRequestParams?: any): Observable<SubscriptionPlan>;

    /**
     * 
     * 
     * @endpoint put /api/SubscriptionPlans/{id}
     * @param id 
     * @param subscriptionPlan 
     */
    apiSubscriptionPlansIdPut(id: number, subscriptionPlan?: SubscriptionPlan, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/SubscriptionPlans
     * @param subscriptionPlan 
     */
    apiSubscriptionPlansPost(subscriptionPlan?: SubscriptionPlan, extraHttpRequestParams?: any): Observable<{}>;

}
