/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface ApiKey { 
    apiKeyId?: number;
    tenantId?: number;
    userId?: number;
    keyName?: string | null;
    keyHash?: string | null;
    keyPrefix?: string | null;
    scope?: string | null;
    isActive?: boolean;
    lastUsedAt?: string | null;
    rateLimit?: number | null;
    expiresAt?: string | null;
    createdAt?: string;
    revokedAt?: string | null;
    tenant?: Tenant;
}

