/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface AuthenticationMethod { 
    authMethodId?: number;
    userId?: number;
    methodType?: string | null;
    isEnabled?: boolean;
    isPrimary?: boolean;
    configuration?: string | null;
    lastUsedAt?: string | null;
    createdAt?: string;
    updatedAt?: string;
    user?: User;
}

