/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface LoginHistory { 
    historyId?: number;
    ipAddress?: string | null;
    deviceInfo?: string | null;
    createdAt?: string;
    user?: User;
    userId?: number;
    userAgent?: string | null;
    loginAt?: string;
    failureReason?: string | null;
    isSuccess?: boolean;
}

