/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PlanDuration = {
    NUMBER_1: 1,
    NUMBER_3: 3,
    NUMBER_6: 6,
    NUMBER_12: 12,
    NUMBER_999: 999
} as const;
export type PlanDuration = typeof PlanDuration[keyof typeof PlanDuration];

