/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SubscriptionPlan } from './subscription-plan';


export interface SubscriptionFeature { 
    subscriptionPlanId?: number;
    featureName?: string | null;
    featureCode?: string | null;
    description?: string | null;
    isEnabled?: boolean;
    limit?: number | null;
    configuration?: string | null;
    displayOrder?: number;
    subscriptionPlan?: SubscriptionPlan;
}

