/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSubscription } from './user-subscription';
import { PlanDuration } from './plan-duration';
import { PlanType } from './plan-type';
import { SubscriptionFeature } from './subscription-feature';


export interface SubscriptionPlan { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    name?: string | null;
    description?: string | null;
    code?: string | null;
    price?: number;
    currency?: string | null;
    type?: PlanType;
    duration?: PlanDuration;
    durationInDays?: number;
    isActive?: boolean;
    isPopular?: boolean;
    maxProfiles?: number;
    maxMatches?: number;
    maxMessages?: number;
    maxPhotos?: number;
    hasPrioritySupport?: boolean;
    hasAdvancedSearch?: boolean;
    hasProfileVerification?: boolean;
    hasMatchRecommendations?: boolean;
    canViewContactDetails?: boolean;
    canSendMessages?: boolean;
    features?: string | null;
    displayOrder?: number;
    userSubscriptions?: Array<UserSubscription> | null;
    subscriptionFeatures?: Array<SubscriptionFeature> | null;
}
export namespace SubscriptionPlan {
}


