/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserSettings { 
    userId?: number;
    profileVisibility?: string | null;
    emailAlerts?: boolean;
    smsAlerts?: boolean;
    eventReminders?: boolean;
    createdAt?: string;
    updatedAt?: string;
    user?: User;
}

