/**
 * Matrimonial SaaS - Match Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MatchProfile } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface MatchProfilesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/MatchProfiles/by-user/{userId}
     * @param userId 
     * @param tenantId 
     */
    apiMatchProfilesByUserUserIdGet(userId: number, tenantId?: number, extraHttpRequestParams?: any): Observable<Array<MatchProfile>>;

    /**
     * 
     * 
     * @endpoint delete /api/MatchProfiles/{id}
     * @param id 
     * @param tenantId 
     */
    apiMatchProfilesIdDelete(id: number, tenantId?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/MatchProfiles/{id}
     * @param id 
     * @param tenantId 
     */
    apiMatchProfilesIdGet(id: number, tenantId?: number, extraHttpRequestParams?: any): Observable<MatchProfile>;

    /**
     * 
     * 
     * @endpoint put /api/MatchProfiles/{id}
     * @param id 
     * @param matchProfile 
     */
    apiMatchProfilesIdPut(id: number, matchProfile?: MatchProfile, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/MatchProfiles
     * @param matchProfile 
     */
    apiMatchProfilesPost(matchProfile?: MatchProfile, extraHttpRequestParams?: any): Observable<{}>;

}
