/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Tenant } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface TenantsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/Tenants
     */
    apiTenantsGet(extraHttpRequestParams?: any): Observable<Array<Tenant>>;

    /**
     * 
     * 
     * @endpoint delete /api/Tenants/{id}
     * @param id 
     */
    apiTenantsIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/Tenants/{id}
     * @param id 
     */
    apiTenantsIdGet(id: number, extraHttpRequestParams?: any): Observable<Tenant>;

    /**
     * 
     * 
     * @endpoint put /api/Tenants/{id}
     * @param id 
     * @param tenant 
     */
    apiTenantsIdPut(id: number, tenant?: Tenant, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/Tenants
     * @param tenant 
     */
    apiTenantsPost(tenant?: Tenant, extraHttpRequestParams?: any): Observable<{}>;

}
