/**
 * Profile Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { MemberProfileDto } from '../model/models';
import { PublicProfileDto } from '../model/models';
import { PublicProfileDtoPagedResult } from '../model/models';
import { UserProfile } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UserProfilesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/UserProfiles
     */
    apiUserProfilesGet(extraHttpRequestParams?: any): Observable<Array<MemberProfileDto>>;

    /**
     * 
     * 
     * @endpoint delete /api/UserProfiles/{id}
     * @param id 
     */
    apiUserProfilesIdDelete(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/UserProfiles/{id}
     * @param id 
     */
    apiUserProfilesIdGet(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint put /api/UserProfiles/{id}
     * @param id 
     * @param userProfile 
     */
    apiUserProfilesIdPut(id: number, userProfile?: UserProfile, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/UserProfiles
     * @param userProfile 
     */
    apiUserProfilesPost(userProfile?: UserProfile, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/UserProfiles/public/{id}
     * @param id 
     */
    apiUserProfilesPublicIdGet(id: number, extraHttpRequestParams?: any): Observable<PublicProfileDto>;

    /**
     * 
     * 
     * @endpoint get /api/UserProfiles/public/search
     * @param tenantId 
     * @param gender 
     * @param ageFrom 
     * @param ageTo 
     * @param religion 
     * @param caste 
     * @param maritalStatus 
     * @param city 
     * @param state 
     * @param country 
     * @param heightFrom 
     * @param heightTo 
     * @param annualIncomeFrom 
     * @param annualIncomeTo 
     * @param isVerified 
     * @param pageNumber 
     * @param pageSize 
     * @param searchTerm 
     * @param sortBy 
     * @param sortDescending 
     */
    apiUserProfilesPublicSearchGet(tenantId?: number, gender?: string, ageFrom?: number, ageTo?: number, religion?: string, caste?: string, maritalStatus?: string, city?: string, state?: string, country?: string, heightFrom?: number, heightTo?: number, annualIncomeFrom?: number, annualIncomeTo?: number, isVerified?: boolean, pageNumber?: number, pageSize?: number, searchTerm?: string, sortBy?: string, sortDescending?: boolean, extraHttpRequestParams?: any): Observable<PublicProfileDtoPagedResult>;

}
