/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface Notification { 
    notificationId?: number;
    notificationText?: string | null;
    createdAt?: string;
    user?: User;
    userId?: number;
    isRead?: boolean;
}

