/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { OAuth2Provider } from './o-auth2-provider';


export interface OAuth2Token { 
    tokenId?: number;
    userId?: number;
    providerId?: number;
    accessToken?: string | null;
    refreshToken?: string | null;
    tokenType?: string | null;
    scope?: string | null;
    expiresAt?: string;
    createdAt?: string;
    user?: User;
    provider?: OAuth2Provider;
}

