/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { UserPermission } from './user-permission';


export interface Permission { 
    permissionId?: number;
    tenantId?: number;
    permissionCode?: string | null;
    displayName?: string | null;
    description?: string | null;
    resourceType?: string | null;
    action?: string | null;
    isActive?: boolean;
    createdAt?: string;
    tenant?: Tenant;
    userPermissions?: Array<UserPermission> | null;
}

