/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface TenantSubscription { 
    subscriptionId?: number;
    tenantId?: number;
    planId?: number;
    startDate?: string;
    endDate?: string;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
    rowVersion?: string | null;
    tenant?: Tenant;
}

