/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface TenantSetting { 
    settingId?: number;
    settingKey?: string | null;
    settingValue?: string | null;
    createdAt?: string;
    updatedAt?: string;
    rowVersion?: string | null;
    tenant?: Tenant;
    tenantId?: number;
}

