/**
 * Matrimonial SaaS - Subscription Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { TenantSetting } from './tenant-setting';
import { ApiKey } from './api-key';
import { User } from './user';
import { TenantFeature } from './tenant-feature';
import { OAuth2Provider } from './o-auth2-provider';
import { TenantUserPlan } from './tenant-user-plan';
import { TenantSubscription } from './tenant-subscription';
import { Permission } from './permission';


export interface Tenant { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    tenantId?: number;
    tenantCode?: string | null;
    domain?: string | null;
    subscriptionStatus?: string | null;
    trialEndDate?: string | null;
    isActive?: boolean;
    rowVersion?: string | null;
    tenantName?: string | null;
    domainName?: string | null;
    tenantFeatures?: Array<TenantFeature> | null;
    users?: Array<User> | null;
    tenantSubscriptions?: Array<TenantSubscription> | null;
    tenantUserPlans?: Array<TenantUserPlan> | null;
    tenantSettings?: Array<TenantSetting> | null;
    roles?: Array<Role> | null;
    permissions?: Array<Permission> | null;
    oAuth2Providers?: Array<OAuth2Provider> | null;
    apiKeys?: Array<ApiKey> | null;
}

