/**
 * Matrimonial SaaS - Match Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InteractionType } from './interaction-type';
import { MatchProfile } from './match-profile';
import { MatchRequest } from './match-request';


export interface MatchInteraction { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    profileId?: number;
    targetProfileId?: number;
    userId?: number;
    tenantId?: number;
    matchRequestId?: number | null;
    type?: InteractionType;
    message?: string | null;
    additionalData?: string | null;
    interactionDate?: string;
    isPositive?: boolean;
    rating?: number;
    notes?: string | null;
    profile?: MatchProfile;
    targetProfile?: MatchProfile;
    matchRequest?: MatchRequest;
}
export namespace MatchInteraction {
}


