/**
 * Matrimonial SaaS - Match Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchProfile } from './match-profile';
import { RecommendationStatus } from './recommendation-status';
import { RecommendationReason } from './recommendation-reason';


export interface MatchRecommendation { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    profileId?: number;
    recommendedProfileId?: number;
    userId?: number;
    tenantId?: number;
    compatibilityScore?: number;
    matchingFactors?: string | null;
    primaryReason?: RecommendationReason;
    reasonDescription?: string | null;
    status?: RecommendationStatus;
    isViewed?: boolean;
    viewedDate?: string;
    isInterested?: boolean;
    isRejected?: boolean;
    interactionDate?: string | null;
    displayOrder?: number;
    generatedDate?: string;
    expiryDate?: string;
    algorithmVersion?: string | null;
    profile?: MatchProfile;
    recommendedProfile?: MatchProfile;
}
export namespace MatchRecommendation {
}


