/**
 * Matrimonial SaaS - Match Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchInteraction } from './match-interaction';
import { MatchProfile } from './match-profile';
import { MatchRequestStatus } from './match-request-status';
import { MatchRequestType } from './match-request-type';


export interface MatchRequest { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    senderProfileId?: number;
    receiverProfileId?: number;
    senderUserId?: number;
    receiverUserId?: number;
    tenantId?: number;
    status?: MatchRequestStatus;
    requestType?: MatchRequestType;
    message?: string | null;
    sentDate?: string;
    responseDate?: string | null;
    expiryDate?: string | null;
    responseMessage?: string | null;
    declineReason?: string | null;
    isRead?: boolean;
    canViewContact?: boolean;
    canSendMessage?: boolean;
    priority?: number;
    notes?: string | null;
    senderProfile?: MatchProfile;
    receiverProfile?: MatchProfile;
    interactions?: Array<MatchInteraction> | null;
}
export namespace MatchRequest {
}


