/**
 * Matrimonial SaaS - Match Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MatchInteraction } from './match-interaction';
import { MatchRequest } from './match-request';
import { MatchRecommendation } from './match-recommendation';


export interface MatchProfile { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    profileId?: number;
    userId?: number;
    tenantId?: number;
    firstName?: string | null;
    lastName?: string | null;
    dateOfBirth?: string;
    age?: number;
    gender?: string | null;
    religion?: string | null;
    caste?: string | null;
    subCaste?: string | null;
    motherTongue?: string | null;
    maritalStatus?: string | null;
    heightInCm?: number;
    educationLevel?: string | null;
    occupation?: string | null;
    annualIncome?: number | null;
    workLocation?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    familyType?: string | null;
    familyValues?: string | null;
    aboutMe?: string | null;
    profilePhotoUrl?: string | null;
    isActive?: boolean;
    isVerified?: boolean;
    isPublic?: boolean;
    lastActiveDate?: string;
    viewCount?: number;
    contactViewCount?: number;
    sentRequests?: Array<MatchRequest> | null;
    receivedRequests?: Array<MatchRequest> | null;
    recommendations?: Array<MatchRecommendation> | null;
    sentInteractions?: Array<MatchInteraction> | null;
    receivedInteractions?: Array<MatchInteraction> | null;
}

