/**
 * Matrimonial SaaS - Chat Service
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChatConversation } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ChatConversationsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @endpoint get /api/ChatConversations/by-user/{userId}
     * @param userId 
     * @param tenantId 
     */
    apiChatConversationsByUserUserIdGet(userId: number, tenantId?: number, extraHttpRequestParams?: any): Observable<Array<ChatConversation>>;

    /**
     * 
     * 
     * @endpoint delete /api/ChatConversations/{id}
     * @param id 
     * @param tenantId 
     */
    apiChatConversationsIdDelete(id: number, tenantId?: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint get /api/ChatConversations/{id}
     * @param id 
     * @param tenantId 
     */
    apiChatConversationsIdGet(id: number, tenantId?: number, extraHttpRequestParams?: any): Observable<ChatConversation>;

    /**
     * 
     * 
     * @endpoint put /api/ChatConversations/{id}
     * @param id 
     * @param chatConversation 
     */
    apiChatConversationsIdPut(id: number, chatConversation?: ChatConversation, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @endpoint post /api/ChatConversations
     * @param chatConversation 
     */
    apiChatConversationsPost(chatConversation?: ChatConversation, extraHttpRequestParams?: any): Observable<{}>;

}
