//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class MatchServiceClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    matchProfilesGET(id: number, tenantId: number | undefined): Promise<MatchProfile> {
        let url_ = this.baseUrl + "/api/MatchProfiles/{id}?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMatchProfilesGET(_response);
        });
    }

    protected processMatchProfilesGET(response: Response): Promise<MatchProfile> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = MatchProfile.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MatchProfile>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    matchProfilesPUT(id: number, body: MatchProfile | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/MatchProfiles/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMatchProfilesPUT(_response);
        });
    }

    protected processMatchProfilesPUT(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    matchProfilesDELETE(id: number, tenantId: number | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/MatchProfiles/{id}?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMatchProfilesDELETE(_response);
        });
    }

    protected processMatchProfilesDELETE(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    byUser(userId: number, tenantId: number | undefined): Promise<MatchProfile[]> {
        let url_ = this.baseUrl + "/api/MatchProfiles/by-user/{userId}?";
        if (userId === undefined || userId === null)
            throw new globalThis.Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processByUser(_response);
        });
    }

    protected processByUser(response: Response): Promise<MatchProfile[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(MatchProfile.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<MatchProfile[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    matchProfilesPOST(body: MatchProfile | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/MatchProfiles";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processMatchProfilesPOST(_response);
        });
    }

    protected processMatchProfilesPOST(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export enum InteractionType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
    _7 = 7,
    _8 = 8,
    _9 = 9,
    _10 = 10,
    _11 = 11,
    _12 = 12,
    _13 = 13,
    _14 = 14,
}

export class MatchInteraction implements IMatchInteraction {
    id?: number;
    profileId?: number;
    targetProfileId?: number;
    userId?: number;
    tenantId?: number;
    matchRequestId?: number | undefined;
    type?: InteractionType;
    message?: string | undefined;
    additionalData?: string | undefined;
    interactionDate?: Date;
    isPositive?: boolean;
    rating?: number;
    notes?: string | undefined;
    profile?: MatchProfile;
    targetProfile?: MatchProfile;
    matchRequest?: MatchRequest;

    constructor(data?: IMatchInteraction) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.profileId = _data["profileId"];
            this.targetProfileId = _data["targetProfileId"];
            this.userId = _data["userId"];
            this.tenantId = _data["tenantId"];
            this.matchRequestId = _data["matchRequestId"];
            this.type = _data["type"];
            this.message = _data["message"];
            this.additionalData = _data["additionalData"];
            this.interactionDate = _data["interactionDate"] ? new Date(_data["interactionDate"].toString()) : undefined as any;
            this.isPositive = _data["isPositive"];
            this.rating = _data["rating"];
            this.notes = _data["notes"];
            this.profile = _data["profile"] ? MatchProfile.fromJS(_data["profile"]) : undefined as any;
            this.targetProfile = _data["targetProfile"] ? MatchProfile.fromJS(_data["targetProfile"]) : undefined as any;
            this.matchRequest = _data["matchRequest"] ? MatchRequest.fromJS(_data["matchRequest"]) : undefined as any;
        }
    }

    static fromJS(data: any): MatchInteraction {
        data = typeof data === 'object' ? data : {};
        let result = new MatchInteraction();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["profileId"] = this.profileId;
        data["targetProfileId"] = this.targetProfileId;
        data["userId"] = this.userId;
        data["tenantId"] = this.tenantId;
        data["matchRequestId"] = this.matchRequestId;
        data["type"] = this.type;
        data["message"] = this.message;
        data["additionalData"] = this.additionalData;
        data["interactionDate"] = this.interactionDate ? this.interactionDate.toISOString() : undefined as any;
        data["isPositive"] = this.isPositive;
        data["rating"] = this.rating;
        data["notes"] = this.notes;
        data["profile"] = this.profile ? this.profile.toJSON() : undefined as any;
        data["targetProfile"] = this.targetProfile ? this.targetProfile.toJSON() : undefined as any;
        data["matchRequest"] = this.matchRequest ? this.matchRequest.toJSON() : undefined as any;
        return data;
    }
}

export interface IMatchInteraction {
    id?: number;
    profileId?: number;
    targetProfileId?: number;
    userId?: number;
    tenantId?: number;
    matchRequestId?: number | undefined;
    type?: InteractionType;
    message?: string | undefined;
    additionalData?: string | undefined;
    interactionDate?: Date;
    isPositive?: boolean;
    rating?: number;
    notes?: string | undefined;
    profile?: MatchProfile;
    targetProfile?: MatchProfile;
    matchRequest?: MatchRequest;
}

export class MatchProfile implements IMatchProfile {
    id?: number;
    createdAt?: Date;
    profileId?: number;
    userId?: number;
    tenantId?: number;
    firstName?: string | undefined;
    lastName?: string | undefined;
    dateOfBirth?: Date;
    age?: number;
    gender?: string | undefined;
    religion?: string | undefined;
    caste?: string | undefined;
    subCaste?: string | undefined;
    motherTongue?: string | undefined;
    maritalStatus?: string | undefined;
    heightInCm?: number;
    educationLevel?: string | undefined;
    occupation?: string | undefined;
    annualIncome?: number | undefined;
    workLocation?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    familyType?: string | undefined;
    familyValues?: string | undefined;
    aboutMe?: string | undefined;
    profilePhotoUrl?: string | undefined;
    isActive?: boolean;
    isVerified?: boolean;
    isPublic?: boolean;
    lastActiveDate?: Date;
    viewCount?: number;
    contactViewCount?: number;
    sentRequests?: MatchRequest[] | undefined;
    receivedRequests?: MatchRequest[] | undefined;
    recommendations?: MatchRecommendation[] | undefined;
    sentInteractions?: MatchInteraction[] | undefined;
    receivedInteractions?: MatchInteraction[] | undefined;

    constructor(data?: IMatchProfile) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.profileId = _data["profileId"];
            this.userId = _data["userId"];
            this.tenantId = _data["tenantId"];
            this.firstName = _data["firstName"];
            this.lastName = _data["lastName"];
            this.dateOfBirth = _data["dateOfBirth"] ? new Date(_data["dateOfBirth"].toString()) : undefined as any;
            this.age = _data["age"];
            this.gender = _data["gender"];
            this.religion = _data["religion"];
            this.caste = _data["caste"];
            this.subCaste = _data["subCaste"];
            this.motherTongue = _data["motherTongue"];
            this.maritalStatus = _data["maritalStatus"];
            this.heightInCm = _data["heightInCm"];
            this.educationLevel = _data["educationLevel"];
            this.occupation = _data["occupation"];
            this.annualIncome = _data["annualIncome"];
            this.workLocation = _data["workLocation"];
            this.city = _data["city"];
            this.state = _data["state"];
            this.country = _data["country"];
            this.familyType = _data["familyType"];
            this.familyValues = _data["familyValues"];
            this.aboutMe = _data["aboutMe"];
            this.profilePhotoUrl = _data["profilePhotoUrl"];
            this.isActive = _data["isActive"];
            this.isVerified = _data["isVerified"];
            this.isPublic = _data["isPublic"];
            this.lastActiveDate = _data["lastActiveDate"] ? new Date(_data["lastActiveDate"].toString()) : undefined as any;
            this.viewCount = _data["viewCount"];
            this.contactViewCount = _data["contactViewCount"];
            if (Array.isArray(_data["sentRequests"])) {
                this.sentRequests = [] as any;
                for (let item of _data["sentRequests"])
                    this.sentRequests!.push(MatchRequest.fromJS(item));
            }
            if (Array.isArray(_data["receivedRequests"])) {
                this.receivedRequests = [] as any;
                for (let item of _data["receivedRequests"])
                    this.receivedRequests!.push(MatchRequest.fromJS(item));
            }
            if (Array.isArray(_data["recommendations"])) {
                this.recommendations = [] as any;
                for (let item of _data["recommendations"])
                    this.recommendations!.push(MatchRecommendation.fromJS(item));
            }
            if (Array.isArray(_data["sentInteractions"])) {
                this.sentInteractions = [] as any;
                for (let item of _data["sentInteractions"])
                    this.sentInteractions!.push(MatchInteraction.fromJS(item));
            }
            if (Array.isArray(_data["receivedInteractions"])) {
                this.receivedInteractions = [] as any;
                for (let item of _data["receivedInteractions"])
                    this.receivedInteractions!.push(MatchInteraction.fromJS(item));
            }
        }
    }

    static fromJS(data: any): MatchProfile {
        data = typeof data === 'object' ? data : {};
        let result = new MatchProfile();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["profileId"] = this.profileId;
        data["userId"] = this.userId;
        data["tenantId"] = this.tenantId;
        data["firstName"] = this.firstName;
        data["lastName"] = this.lastName;
        data["dateOfBirth"] = this.dateOfBirth ? this.dateOfBirth.toISOString() : undefined as any;
        data["age"] = this.age;
        data["gender"] = this.gender;
        data["religion"] = this.religion;
        data["caste"] = this.caste;
        data["subCaste"] = this.subCaste;
        data["motherTongue"] = this.motherTongue;
        data["maritalStatus"] = this.maritalStatus;
        data["heightInCm"] = this.heightInCm;
        data["educationLevel"] = this.educationLevel;
        data["occupation"] = this.occupation;
        data["annualIncome"] = this.annualIncome;
        data["workLocation"] = this.workLocation;
        data["city"] = this.city;
        data["state"] = this.state;
        data["country"] = this.country;
        data["familyType"] = this.familyType;
        data["familyValues"] = this.familyValues;
        data["aboutMe"] = this.aboutMe;
        data["profilePhotoUrl"] = this.profilePhotoUrl;
        data["isActive"] = this.isActive;
        data["isVerified"] = this.isVerified;
        data["isPublic"] = this.isPublic;
        data["lastActiveDate"] = this.lastActiveDate ? this.lastActiveDate.toISOString() : undefined as any;
        data["viewCount"] = this.viewCount;
        data["contactViewCount"] = this.contactViewCount;
        if (Array.isArray(this.sentRequests)) {
            data["sentRequests"] = [];
            for (let item of this.sentRequests)
                data["sentRequests"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.receivedRequests)) {
            data["receivedRequests"] = [];
            for (let item of this.receivedRequests)
                data["receivedRequests"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.recommendations)) {
            data["recommendations"] = [];
            for (let item of this.recommendations)
                data["recommendations"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.sentInteractions)) {
            data["sentInteractions"] = [];
            for (let item of this.sentInteractions)
                data["sentInteractions"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.receivedInteractions)) {
            data["receivedInteractions"] = [];
            for (let item of this.receivedInteractions)
                data["receivedInteractions"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IMatchProfile {
    id?: number;
    createdAt?: Date;
    profileId?: number;
    userId?: number;
    tenantId?: number;
    firstName?: string | undefined;
    lastName?: string | undefined;
    dateOfBirth?: Date;
    age?: number;
    gender?: string | undefined;
    religion?: string | undefined;
    caste?: string | undefined;
    subCaste?: string | undefined;
    motherTongue?: string | undefined;
    maritalStatus?: string | undefined;
    heightInCm?: number;
    educationLevel?: string | undefined;
    occupation?: string | undefined;
    annualIncome?: number | undefined;
    workLocation?: string | undefined;
    city?: string | undefined;
    state?: string | undefined;
    country?: string | undefined;
    familyType?: string | undefined;
    familyValues?: string | undefined;
    aboutMe?: string | undefined;
    profilePhotoUrl?: string | undefined;
    isActive?: boolean;
    isVerified?: boolean;
    isPublic?: boolean;
    lastActiveDate?: Date;
    viewCount?: number;
    contactViewCount?: number;
    sentRequests?: MatchRequest[] | undefined;
    receivedRequests?: MatchRequest[] | undefined;
    recommendations?: MatchRecommendation[] | undefined;
    sentInteractions?: MatchInteraction[] | undefined;
    receivedInteractions?: MatchInteraction[] | undefined;
}

export class MatchRecommendation implements IMatchRecommendation {
    id?: number;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    isDeleted?: boolean;
    createdBy?: number | undefined;
    updatedBy?: number | undefined;
    profileId?: number;
    recommendedProfileId?: number;
    userId?: number;
    tenantId?: number;
    compatibilityScore?: number;
    matchingFactors?: string | undefined;
    primaryReason?: RecommendationReason;
    reasonDescription?: string | undefined;
    status?: RecommendationStatus;
    isViewed?: boolean;
    viewedDate?: Date;
    isInterested?: boolean;
    isRejected?: boolean;
    interactionDate?: Date | undefined;
    displayOrder?: number;
    generatedDate?: Date;
    expiryDate?: Date;
    algorithmVersion?: string | undefined;
    profile?: MatchProfile;
    recommendedProfile?: MatchProfile;

    constructor(data?: IMatchRecommendation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
            this.isDeleted = _data["isDeleted"];
            this.createdBy = _data["createdBy"];
            this.updatedBy = _data["updatedBy"];
            this.profileId = _data["profileId"];
            this.recommendedProfileId = _data["recommendedProfileId"];
            this.userId = _data["userId"];
            this.tenantId = _data["tenantId"];
            this.compatibilityScore = _data["compatibilityScore"];
            this.matchingFactors = _data["matchingFactors"];
            this.primaryReason = _data["primaryReason"];
            this.reasonDescription = _data["reasonDescription"];
            this.status = _data["status"];
            this.isViewed = _data["isViewed"];
            this.viewedDate = _data["viewedDate"] ? new Date(_data["viewedDate"].toString()) : undefined as any;
            this.isInterested = _data["isInterested"];
            this.isRejected = _data["isRejected"];
            this.interactionDate = _data["interactionDate"] ? new Date(_data["interactionDate"].toString()) : undefined as any;
            this.displayOrder = _data["displayOrder"];
            this.generatedDate = _data["generatedDate"] ? new Date(_data["generatedDate"].toString()) : undefined as any;
            this.expiryDate = _data["expiryDate"] ? new Date(_data["expiryDate"].toString()) : undefined as any;
            this.algorithmVersion = _data["algorithmVersion"];
            this.profile = _data["profile"] ? MatchProfile.fromJS(_data["profile"]) : undefined as any;
            this.recommendedProfile = _data["recommendedProfile"] ? MatchProfile.fromJS(_data["recommendedProfile"]) : undefined as any;
        }
    }

    static fromJS(data: any): MatchRecommendation {
        data = typeof data === 'object' ? data : {};
        let result = new MatchRecommendation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        data["isDeleted"] = this.isDeleted;
        data["createdBy"] = this.createdBy;
        data["updatedBy"] = this.updatedBy;
        data["profileId"] = this.profileId;
        data["recommendedProfileId"] = this.recommendedProfileId;
        data["userId"] = this.userId;
        data["tenantId"] = this.tenantId;
        data["compatibilityScore"] = this.compatibilityScore;
        data["matchingFactors"] = this.matchingFactors;
        data["primaryReason"] = this.primaryReason;
        data["reasonDescription"] = this.reasonDescription;
        data["status"] = this.status;
        data["isViewed"] = this.isViewed;
        data["viewedDate"] = this.viewedDate ? this.viewedDate.toISOString() : undefined as any;
        data["isInterested"] = this.isInterested;
        data["isRejected"] = this.isRejected;
        data["interactionDate"] = this.interactionDate ? this.interactionDate.toISOString() : undefined as any;
        data["displayOrder"] = this.displayOrder;
        data["generatedDate"] = this.generatedDate ? this.generatedDate.toISOString() : undefined as any;
        data["expiryDate"] = this.expiryDate ? this.expiryDate.toISOString() : undefined as any;
        data["algorithmVersion"] = this.algorithmVersion;
        data["profile"] = this.profile ? this.profile.toJSON() : undefined as any;
        data["recommendedProfile"] = this.recommendedProfile ? this.recommendedProfile.toJSON() : undefined as any;
        return data;
    }
}

export interface IMatchRecommendation {
    id?: number;
    createdAt?: Date;
    updatedAt?: Date | undefined;
    isDeleted?: boolean;
    createdBy?: number | undefined;
    updatedBy?: number | undefined;
    profileId?: number;
    recommendedProfileId?: number;
    userId?: number;
    tenantId?: number;
    compatibilityScore?: number;
    matchingFactors?: string | undefined;
    primaryReason?: RecommendationReason;
    reasonDescription?: string | undefined;
    status?: RecommendationStatus;
    isViewed?: boolean;
    viewedDate?: Date;
    isInterested?: boolean;
    isRejected?: boolean;
    interactionDate?: Date | undefined;
    displayOrder?: number;
    generatedDate?: Date;
    expiryDate?: Date;
    algorithmVersion?: string | undefined;
    profile?: MatchProfile;
    recommendedProfile?: MatchProfile;
}

export class MatchRequest implements IMatchRequest {
    id?: number;
    createdAt?: Date;
    senderProfileId?: number;
    receiverProfileId?: number;
    senderUserId?: number;
    receiverUserId?: number;
    tenantId?: number;
    status?: MatchRequestStatus;
    requestType?: MatchRequestType;
    message?: string | undefined;
    sentDate?: Date;
    responseDate?: Date | undefined;
    expiryDate?: Date | undefined;
    responseMessage?: string | undefined;
    declineReason?: string | undefined;
    isRead?: boolean;
    canViewContact?: boolean;
    canSendMessage?: boolean;
    priority?: number;
    notes?: string | undefined;
    senderProfile?: MatchProfile;
    receiverProfile?: MatchProfile;
    interactions?: MatchInteraction[] | undefined;

    constructor(data?: IMatchRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.senderProfileId = _data["senderProfileId"];
            this.receiverProfileId = _data["receiverProfileId"];
            this.senderUserId = _data["senderUserId"];
            this.receiverUserId = _data["receiverUserId"];
            this.tenantId = _data["tenantId"];
            this.status = _data["status"];
            this.requestType = _data["requestType"];
            this.message = _data["message"];
            this.sentDate = _data["sentDate"] ? new Date(_data["sentDate"].toString()) : undefined as any;
            this.responseDate = _data["responseDate"] ? new Date(_data["responseDate"].toString()) : undefined as any;
            this.expiryDate = _data["expiryDate"] ? new Date(_data["expiryDate"].toString()) : undefined as any;
            this.responseMessage = _data["responseMessage"];
            this.declineReason = _data["declineReason"];
            this.isRead = _data["isRead"];
            this.canViewContact = _data["canViewContact"];
            this.canSendMessage = _data["canSendMessage"];
            this.priority = _data["priority"];
            this.notes = _data["notes"];
            this.senderProfile = _data["senderProfile"] ? MatchProfile.fromJS(_data["senderProfile"]) : undefined as any;
            this.receiverProfile = _data["receiverProfile"] ? MatchProfile.fromJS(_data["receiverProfile"]) : undefined as any;
            if (Array.isArray(_data["interactions"])) {
                this.interactions = [] as any;
                for (let item of _data["interactions"])
                    this.interactions!.push(MatchInteraction.fromJS(item));
            }
        }
    }

    static fromJS(data: any): MatchRequest {
        data = typeof data === 'object' ? data : {};
        let result = new MatchRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["senderProfileId"] = this.senderProfileId;
        data["receiverProfileId"] = this.receiverProfileId;
        data["senderUserId"] = this.senderUserId;
        data["receiverUserId"] = this.receiverUserId;
        data["tenantId"] = this.tenantId;
        data["status"] = this.status;
        data["requestType"] = this.requestType;
        data["message"] = this.message;
        data["sentDate"] = this.sentDate ? this.sentDate.toISOString() : undefined as any;
        data["responseDate"] = this.responseDate ? this.responseDate.toISOString() : undefined as any;
        data["expiryDate"] = this.expiryDate ? this.expiryDate.toISOString() : undefined as any;
        data["responseMessage"] = this.responseMessage;
        data["declineReason"] = this.declineReason;
        data["isRead"] = this.isRead;
        data["canViewContact"] = this.canViewContact;
        data["canSendMessage"] = this.canSendMessage;
        data["priority"] = this.priority;
        data["notes"] = this.notes;
        data["senderProfile"] = this.senderProfile ? this.senderProfile.toJSON() : undefined as any;
        data["receiverProfile"] = this.receiverProfile ? this.receiverProfile.toJSON() : undefined as any;
        if (Array.isArray(this.interactions)) {
            data["interactions"] = [];
            for (let item of this.interactions)
                data["interactions"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IMatchRequest {
    id?: number;
    createdAt?: Date;
    senderProfileId?: number;
    receiverProfileId?: number;
    senderUserId?: number;
    receiverUserId?: number;
    tenantId?: number;
    status?: MatchRequestStatus;
    requestType?: MatchRequestType;
    message?: string | undefined;
    sentDate?: Date;
    responseDate?: Date | undefined;
    expiryDate?: Date | undefined;
    responseMessage?: string | undefined;
    declineReason?: string | undefined;
    isRead?: boolean;
    canViewContact?: boolean;
    canSendMessage?: boolean;
    priority?: number;
    notes?: string | undefined;
    senderProfile?: MatchProfile;
    receiverProfile?: MatchProfile;
    interactions?: MatchInteraction[] | undefined;
}

export enum MatchRequestStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
}

export enum MatchRequestType {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
}

export enum RecommendationReason {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
    _5 = 5,
    _6 = 6,
    _7 = 7,
    _8 = 8,
    _9 = 9,
    _10 = 10,
}

export enum RecommendationStatus {
    _0 = 0,
    _1 = 1,
    _2 = 2,
    _3 = 3,
    _4 = 4,
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}