//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class MatrimonialSaaS_Services_Subscription_APIClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    gET_diag_plans(): Promise<void> {
        let url_ = this.baseUrl + "/diag/plans";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGET_diag_plans(_response);
        });
    }

    protected processGET_diag_plans(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class PaymentsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    checkout(body: CheckoutRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Payments/checkout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheckout(_response);
        });
    }

    protected processCheckout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class SubscriptionFeaturesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getAll(): Promise<SubscriptionFeatureDto[]> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<SubscriptionFeatureDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionFeatureDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateSubscriptionFeatureRequest | undefined): Promise<SubscriptionFeatureDto> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<SubscriptionFeatureDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionFeatureDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<SubscriptionFeatureDto> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<SubscriptionFeatureDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionFeatureDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateSubscriptionFeatureRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class SubscriptionPlansClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    getAll(tenantId: number | undefined): Promise<SubscriptionPlanDto[]> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans?";
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<SubscriptionPlanDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionPlanDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateSubscriptionPlanRequest | undefined): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }

    /**
     * @return OK
     */
    getAllIncludingInactive(): Promise<SubscriptionPlanDto[]> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllIncludingInactive(_response);
        });
    }

    protected processGetAllIncludingInactive(response: Response): Promise<SubscriptionPlanDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionPlanDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto[]>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateSubscriptionPlanRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getByCode(code: string): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/SubscriptionPlans/code/{code}";
        if (code === undefined || code === null)
            throw new globalThis.Error("The parameter 'code' must be defined.");
        url_ = url_.replace("{code}", encodeURIComponent("" + code));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetByCode(_response);
        });
    }

    protected processGetByCode(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }
}

export class SubscriptionStatusClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getSubscriptionStatus(tenantId: number): Promise<SubscriptionStatusDto> {
        let url_ = this.baseUrl + "/api/subscription/status/{tenantId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSubscriptionStatus(_response);
        });
    }

    protected processGetSubscriptionStatus(response: Response): Promise<SubscriptionStatusDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionStatusDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionStatusDto>(null as any);
    }

    /**
     * @return OK
     */
    getUserSubscriptionStatus(userId: number): Promise<UserSubscriptionStatusDto> {
        let url_ = this.baseUrl + "/api/subscription/user-status/{userId}";
        if (userId === undefined || userId === null)
            throw new globalThis.Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetUserSubscriptionStatus(_response);
        });
    }

    protected processGetUserSubscriptionStatus(response: Response): Promise<UserSubscriptionStatusDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserSubscriptionStatusDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionStatusDto>(null as any);
    }
}

export class TenantPlanExclusionsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getExclusions(tenantId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantPlanExclusions/{tenantId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetExclusions(_response);
        });
    }

    protected processGetExclusions(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    exclude(tenantId: number, planId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantPlanExclusions/{tenantId}/{planId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        if (planId === undefined || planId === null)
            throw new globalThis.Error("The parameter 'planId' must be defined.");
        url_ = url_.replace("{planId}", encodeURIComponent("" + planId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "POST",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processExclude(_response);
        });
    }

    protected processExclude(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    include(tenantId: number, planId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantPlanExclusions/{tenantId}/{planId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        if (planId === undefined || planId === null)
            throw new globalThis.Error("The parameter 'planId' must be defined.");
        url_ = url_.replace("{planId}", encodeURIComponent("" + planId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processInclude(_response);
        });
    }

    protected processInclude(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class TenantPlanPricingClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getOverrides(tenantId: number, planId: number): Promise<TenantPlanFeatureOverrideDto[]> {
        let url_ = this.baseUrl + "/api/TenantPlanPricing/{tenantId}/{planId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        if (planId === undefined || planId === null)
            throw new globalThis.Error("The parameter 'planId' must be defined.");
        url_ = url_.replace("{planId}", encodeURIComponent("" + planId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetOverrides(_response);
        });
    }

    protected processGetOverrides(response: Response): Promise<TenantPlanFeatureOverrideDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TenantPlanFeatureOverrideDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TenantPlanFeatureOverrideDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    setOverrides(tenantId: number, planId: number, body: SetTenantFeatureOverridesRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantPlanPricing/{tenantId}/{planId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        if (planId === undefined || planId === null)
            throw new globalThis.Error("The parameter 'planId' must be defined.");
        url_ = url_.replace("{planId}", encodeURIComponent("" + planId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processSetOverrides(_response);
        });
    }

    protected processSetOverrides(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    clearOverrides(tenantId: number, planId: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantPlanPricing/{tenantId}/{planId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        if (planId === undefined || planId === null)
            throw new globalThis.Error("The parameter 'planId' must be defined.");
        url_ = url_.replace("{planId}", encodeURIComponent("" + planId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processClearOverrides(_response);
        });
    }

    protected processClearOverrides(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class CheckoutRequest implements ICheckoutRequest {
    planId?: number;

    constructor(data?: ICheckoutRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.planId = _data["planId"];
        }
    }

    static fromJS(data: any): CheckoutRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CheckoutRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["planId"] = this.planId;
        return data;
    }
}

export interface ICheckoutRequest {
    planId?: number;
}

export class CreateSubscriptionFeatureRequest implements ICreateSubscriptionFeatureRequest {
    code!: string;
    name!: string;
    description?: string | undefined;
    category!: string;
    dataType!: string;
    defaultValue?: string | undefined;
    isActive?: boolean;

    constructor(data?: ICreateSubscriptionFeatureRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): CreateSubscriptionFeatureRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSubscriptionFeatureRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface ICreateSubscriptionFeatureRequest {
    code: string;
    name: string;
    description?: string | undefined;
    category: string;
    dataType: string;
    defaultValue?: string | undefined;
    isActive?: boolean;
}

export class CreateSubscriptionPlanRequest implements ICreateSubscriptionPlanRequest {
    code!: string;
    name!: string;
    description?: string | undefined;
    price!: number;
    durationMonths!: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: ICreateSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            this.tenantId = _data["tenantId"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        data["tenantId"] = this.tenantId;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICreateSubscriptionPlanRequest {
    code: string;
    name: string;
    description?: string | undefined;
    price: number;
    durationMonths: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    features?: FeatureValueRequest[] | undefined;
}

export class FeatureValueRequest implements IFeatureValueRequest {
    featureCode!: string;
    value!: string;

    constructor(data?: IFeatureValueRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.featureCode = _data["featureCode"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): FeatureValueRequest {
        data = typeof data === 'object' ? data : {};
        let result = new FeatureValueRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["featureCode"] = this.featureCode;
        data["value"] = this.value;
        return data;
    }
}

export interface IFeatureValueRequest {
    featureCode: string;
    value: string;
}

export class PlanFeatureValueDto implements IPlanFeatureValueDto {
    code?: string | undefined;
    name?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    value?: string | undefined;

    constructor(data?: IPlanFeatureValueDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): PlanFeatureValueDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlanFeatureValueDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["value"] = this.value;
        return data;
    }
}

export interface IPlanFeatureValueDto {
    code?: string | undefined;
    name?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    value?: string | undefined;
}

export class SetTenantFeatureOverridesRequest implements ISetTenantFeatureOverridesRequest {
    overrides!: TenantFeatureOverrideRequest[];

    constructor(data?: ISetTenantFeatureOverridesRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
        if (!data) {
            this.overrides = [];
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["overrides"])) {
                this.overrides = [] as any;
                for (let item of _data["overrides"])
                    this.overrides!.push(TenantFeatureOverrideRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SetTenantFeatureOverridesRequest {
        data = typeof data === 'object' ? data : {};
        let result = new SetTenantFeatureOverridesRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.overrides)) {
            data["overrides"] = [];
            for (let item of this.overrides)
                data["overrides"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISetTenantFeatureOverridesRequest {
    overrides: TenantFeatureOverrideRequest[];
}

export class SubscriptionFeatureDto implements ISubscriptionFeatureDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;

    constructor(data?: ISubscriptionFeatureDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): SubscriptionFeatureDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionFeatureDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ISubscriptionFeatureDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export class SubscriptionPlanDto implements ISubscriptionPlanDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;

    constructor(data?: ISubscriptionPlanDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            this.tenantId = _data["tenantId"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(PlanFeatureValueDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SubscriptionPlanDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionPlanDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        data["tenantId"] = this.tenantId;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISubscriptionPlanDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;
}

export class SubscriptionStatusDto implements ISubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    isTrial?: boolean;

    constructor(data?: ISubscriptionStatusDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isActive = _data["isActive"];
            this.isExpired = _data["isExpired"];
            this.planName = _data["planName"];
            this.expiresAt = _data["expiresAt"] ? new Date(_data["expiresAt"].toString()) : undefined as any;
            this.isTrial = _data["isTrial"];
        }
    }

    static fromJS(data: any): SubscriptionStatusDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionStatusDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isActive"] = this.isActive;
        data["isExpired"] = this.isExpired;
        data["planName"] = this.planName;
        data["expiresAt"] = this.expiresAt ? this.expiresAt.toISOString() : undefined as any;
        data["isTrial"] = this.isTrial;
        return data;
    }
}

export interface ISubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    isTrial?: boolean;
}

export class TenantFeatureOverrideRequest implements ITenantFeatureOverrideRequest {
    featureCode!: string;
    value!: string;

    constructor(data?: ITenantFeatureOverrideRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.featureCode = _data["featureCode"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): TenantFeatureOverrideRequest {
        data = typeof data === 'object' ? data : {};
        let result = new TenantFeatureOverrideRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["featureCode"] = this.featureCode;
        data["value"] = this.value;
        return data;
    }
}

export interface ITenantFeatureOverrideRequest {
    featureCode: string;
    value: string;
}

export class TenantPlanFeatureOverrideDto implements ITenantPlanFeatureOverrideDto {
    id?: number;
    tenantId?: number;
    subscriptionPlanId?: number;
    subscriptionFeatureId?: number;
    featureCode?: string | undefined;
    featureName?: string | undefined;
    value?: string | undefined;
    createdAt?: Date;

    constructor(data?: ITenantPlanFeatureOverrideDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.tenantId = _data["tenantId"];
            this.subscriptionPlanId = _data["subscriptionPlanId"];
            this.subscriptionFeatureId = _data["subscriptionFeatureId"];
            this.featureCode = _data["featureCode"];
            this.featureName = _data["featureName"];
            this.value = _data["value"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TenantPlanFeatureOverrideDto {
        data = typeof data === 'object' ? data : {};
        let result = new TenantPlanFeatureOverrideDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["tenantId"] = this.tenantId;
        data["subscriptionPlanId"] = this.subscriptionPlanId;
        data["subscriptionFeatureId"] = this.subscriptionFeatureId;
        data["featureCode"] = this.featureCode;
        data["featureName"] = this.featureName;
        data["value"] = this.value;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ITenantPlanFeatureOverrideDto {
    id?: number;
    tenantId?: number;
    subscriptionPlanId?: number;
    subscriptionFeatureId?: number;
    featureCode?: string | undefined;
    featureName?: string | undefined;
    value?: string | undefined;
    createdAt?: Date;
}

export class UpdateSubscriptionFeatureRequest implements IUpdateSubscriptionFeatureRequest {
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean | undefined;

    constructor(data?: IUpdateSubscriptionFeatureRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): UpdateSubscriptionFeatureRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSubscriptionFeatureRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IUpdateSubscriptionFeatureRequest {
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean | undefined;
}

export class UpdateSubscriptionPlanRequest implements IUpdateSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: IUpdateSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUpdateSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;
}

export class UserSubscriptionStatusDto implements IUserSubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    isTrial?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    effectiveFeatures?: PlanFeatureValueDto[] | undefined;

    constructor(data?: IUserSubscriptionStatusDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isActive = _data["isActive"];
            this.isExpired = _data["isExpired"];
            this.isTrial = _data["isTrial"];
            this.planName = _data["planName"];
            this.expiresAt = _data["expiresAt"] ? new Date(_data["expiresAt"].toString()) : undefined as any;
            if (Array.isArray(_data["effectiveFeatures"])) {
                this.effectiveFeatures = [] as any;
                for (let item of _data["effectiveFeatures"])
                    this.effectiveFeatures!.push(PlanFeatureValueDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserSubscriptionStatusDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserSubscriptionStatusDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isActive"] = this.isActive;
        data["isExpired"] = this.isExpired;
        data["isTrial"] = this.isTrial;
        data["planName"] = this.planName;
        data["expiresAt"] = this.expiresAt ? this.expiresAt.toISOString() : undefined as any;
        if (Array.isArray(this.effectiveFeatures)) {
            data["effectiveFeatures"] = [];
            for (let item of this.effectiveFeatures)
                data["effectiveFeatures"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUserSubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    isTrial?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    effectiveFeatures?: PlanFeatureValueDto[] | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}