//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

export class MatrimonialSaaS_Services_Subscription_APIClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    gET_diag_plans(): Promise<void> {
        let url_ = this.baseUrl + "/diag/plans";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGET_diag_plans(_response);
        });
    }

    protected processGET_diag_plans(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class PaymentsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    checkout(body: CheckoutRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/Payments/checkout";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCheckout(_response);
        });
    }

    protected processCheckout(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class SubscriptionFeaturesClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getAll(): Promise<SubscriptionFeatureDto[]> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<SubscriptionFeatureDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionFeatureDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateSubscriptionFeatureRequest | undefined): Promise<SubscriptionFeatureDto> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<SubscriptionFeatureDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionFeatureDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<SubscriptionFeatureDto> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<SubscriptionFeatureDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionFeatureDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionFeatureDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateSubscriptionFeatureRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/SubscriptionFeatures/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class SubscriptionStatusClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getSubscriptionStatus(tenantId: number): Promise<SubscriptionStatusDto> {
        let url_ = this.baseUrl + "/api/subscription/status/{tenantId}";
        if (tenantId === undefined || tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' must be defined.");
        url_ = url_.replace("{tenantId}", encodeURIComponent("" + tenantId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetSubscriptionStatus(_response);
        });
    }

    protected processGetSubscriptionStatus(response: Response): Promise<SubscriptionStatusDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionStatusDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionStatusDto>(null as any);
    }

    /**
     * @return OK
     */
    getUserSubscriptionStatus(userId: number): Promise<UserSubscriptionStatusDto> {
        let url_ = this.baseUrl + "/api/subscription/user-status/{userId}";
        if (userId === undefined || userId === null)
            throw new globalThis.Error("The parameter 'userId' must be defined.");
        url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetUserSubscriptionStatus(_response);
        });
    }

    protected processGetUserSubscriptionStatus(response: Response): Promise<UserSubscriptionStatusDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserSubscriptionStatusDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionStatusDto>(null as any);
    }
}

export class TenantSubscriptionPlansClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    getAll(tenantId: number | undefined): Promise<SubscriptionPlanDto[]> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans?";
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<SubscriptionPlanDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionPlanDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateSubscriptionPlanRequest | undefined): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }

    /**
     * @return OK
     */
    getAllIncludingInactive(): Promise<SubscriptionPlanDto[]> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans/all";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAllIncludingInactive(_response);
        });
    }

    protected processGetAllIncludingInactive(response: Response): Promise<SubscriptionPlanDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(SubscriptionPlanDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto[]>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateSubscriptionPlanRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getByCode(code: string): Promise<SubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/TenantSubscriptionPlans/code/{code}";
        if (code === undefined || code === null)
            throw new globalThis.Error("The parameter 'code' must be defined.");
        url_ = url_.replace("{code}", encodeURIComponent("" + code));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetByCode(_response);
        });
    }

    protected processGetByCode(response: Response): Promise<SubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = SubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<SubscriptionPlanDto>(null as any);
    }
}

export class TenantSubscriptionsClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param tenantId (optional) 
     * @return OK
     */
    getAll(tenantId: number | undefined): Promise<TenantSubscriptionDto[]> {
        let url_ = this.baseUrl + "/api/TenantSubscriptions?";
        if (tenantId === null)
            throw new globalThis.Error("The parameter 'tenantId' cannot be null.");
        else if (tenantId !== undefined)
            url_ += "tenantId=" + encodeURIComponent("" + tenantId) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<TenantSubscriptionDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(TenantSubscriptionDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TenantSubscriptionDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateTenantSubscriptionRequest | undefined): Promise<TenantSubscriptionDto> {
        let url_ = this.baseUrl + "/api/TenantSubscriptions";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<TenantSubscriptionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TenantSubscriptionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TenantSubscriptionDto>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<TenantSubscriptionDto> {
        let url_ = this.baseUrl + "/api/TenantSubscriptions/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<TenantSubscriptionDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = TenantSubscriptionDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<TenantSubscriptionDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateTenantSubscriptionRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantSubscriptions/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/TenantSubscriptions/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export class UserSubscriptionPlansClient {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @return OK
     */
    getAll(): Promise<UserSubscriptionPlanDto[]> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetAll(_response);
        });
    }

    protected processGetAll(response: Response): Promise<UserSubscriptionPlanDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(UserSubscriptionPlanDto.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionPlanDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    create(body: CreateUserSubscriptionPlanRequest | undefined): Promise<UserSubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreate(_response);
        });
    }

    protected processCreate(response: Response): Promise<UserSubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserSubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionPlanDto>(null as any);
    }

    /**
     * @return OK
     */
    getById(id: number): Promise<UserSubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetById(_response);
        });
    }

    protected processGetById(response: Response): Promise<UserSubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserSubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionPlanDto>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    update(id: number, body: UpdateUserSubscriptionPlanRequest | undefined): Promise<void> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdate(_response);
        });
    }

    protected processUpdate(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    delete(id: number): Promise<void> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDelete(_response);
        });
    }

    protected processDelete(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @return OK
     */
    getByCode(code: string): Promise<UserSubscriptionPlanDto> {
        let url_ = this.baseUrl + "/api/UserSubscriptionPlans/code/{code}";
        if (code === undefined || code === null)
            throw new globalThis.Error("The parameter 'code' must be defined.");
        url_ = url_.replace("{code}", encodeURIComponent("" + code));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            headers: {
                "Accept": "application/json"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetByCode(_response);
        });
    }

    protected processGetByCode(response: Response): Promise<UserSubscriptionPlanDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = UserSubscriptionPlanDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserSubscriptionPlanDto>(null as any);
    }
}

export class CheckoutRequest implements ICheckoutRequest {
    planId?: number;

    constructor(data?: ICheckoutRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.planId = _data["planId"];
        }
    }

    static fromJS(data: any): CheckoutRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CheckoutRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["planId"] = this.planId;
        return data;
    }
}

export interface ICheckoutRequest {
    planId?: number;
}

export class CreateSubscriptionFeatureRequest implements ICreateSubscriptionFeatureRequest {
    code!: string;
    name!: string;
    description?: string | undefined;
    category!: string;
    dataType!: string;
    defaultValue?: string | undefined;
    isActive?: boolean;

    constructor(data?: ICreateSubscriptionFeatureRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): CreateSubscriptionFeatureRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSubscriptionFeatureRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface ICreateSubscriptionFeatureRequest {
    code: string;
    name: string;
    description?: string | undefined;
    category: string;
    dataType: string;
    defaultValue?: string | undefined;
    isActive?: boolean;
}

export class CreateSubscriptionPlanRequest implements ICreateSubscriptionPlanRequest {
    code!: string;
    name!: string;
    description?: string | undefined;
    price!: number;
    durationMonths!: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: ICreateSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            this.tenantId = _data["tenantId"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        data["tenantId"] = this.tenantId;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICreateSubscriptionPlanRequest {
    code: string;
    name: string;
    description?: string | undefined;
    price: number;
    durationMonths: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    features?: FeatureValueRequest[] | undefined;
}

export class CreateTenantSubscriptionRequest implements ICreateTenantSubscriptionRequest {
    tenantId?: number;
    planId?: number;
    startDate?: Date;
    endDate?: Date;

    constructor(data?: ICreateTenantSubscriptionRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.tenantId = _data["tenantId"];
            this.planId = _data["planId"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): CreateTenantSubscriptionRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateTenantSubscriptionRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["tenantId"] = this.tenantId;
        data["planId"] = this.planId;
        data["startDate"] = this.startDate ? formatDate(this.startDate) : undefined as any;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : undefined as any;
        return data;
    }
}

export interface ICreateTenantSubscriptionRequest {
    tenantId?: number;
    planId?: number;
    startDate?: Date;
    endDate?: Date;
}

export class CreateUserSubscriptionPlanRequest implements ICreateUserSubscriptionPlanRequest {
    code!: string;
    name!: string;
    description?: string | undefined;
    price!: number;
    durationMonths!: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: ICreateUserSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): CreateUserSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new CreateUserSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ICreateUserSubscriptionPlanRequest {
    code: string;
    name: string;
    description?: string | undefined;
    price: number;
    durationMonths: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    features?: FeatureValueRequest[] | undefined;
}

export class FeatureValueRequest implements IFeatureValueRequest {
    featureCode!: string;
    value!: string;

    constructor(data?: IFeatureValueRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.featureCode = _data["featureCode"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): FeatureValueRequest {
        data = typeof data === 'object' ? data : {};
        let result = new FeatureValueRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["featureCode"] = this.featureCode;
        data["value"] = this.value;
        return data;
    }
}

export interface IFeatureValueRequest {
    featureCode: string;
    value: string;
}

export class PlanFeatureValueDto implements IPlanFeatureValueDto {
    code?: string | undefined;
    name?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    value?: string | undefined;

    constructor(data?: IPlanFeatureValueDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.code = _data["code"];
            this.name = _data["name"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): PlanFeatureValueDto {
        data = typeof data === 'object' ? data : {};
        let result = new PlanFeatureValueDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["code"] = this.code;
        data["name"] = this.name;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["value"] = this.value;
        return data;
    }
}

export interface IPlanFeatureValueDto {
    code?: string | undefined;
    name?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    value?: string | undefined;
}

export class SubscriptionFeatureDto implements ISubscriptionFeatureDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;

    constructor(data?: ISubscriptionFeatureDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): SubscriptionFeatureDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionFeatureDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ISubscriptionFeatureDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export class SubscriptionPlanDto implements ISubscriptionPlanDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;

    constructor(data?: ISubscriptionPlanDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            this.tenantId = _data["tenantId"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(PlanFeatureValueDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): SubscriptionPlanDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionPlanDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        data["tenantId"] = this.tenantId;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface ISubscriptionPlanDto {
    id?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    tenantId?: number | undefined;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;
}

export class SubscriptionStatusDto implements ISubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    isTrial?: boolean;

    constructor(data?: ISubscriptionStatusDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isActive = _data["isActive"];
            this.isExpired = _data["isExpired"];
            this.planName = _data["planName"];
            this.expiresAt = _data["expiresAt"] ? new Date(_data["expiresAt"].toString()) : undefined as any;
            this.isTrial = _data["isTrial"];
        }
    }

    static fromJS(data: any): SubscriptionStatusDto {
        data = typeof data === 'object' ? data : {};
        let result = new SubscriptionStatusDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isActive"] = this.isActive;
        data["isExpired"] = this.isExpired;
        data["planName"] = this.planName;
        data["expiresAt"] = this.expiresAt ? this.expiresAt.toISOString() : undefined as any;
        data["isTrial"] = this.isTrial;
        return data;
    }
}

export interface ISubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    planName?: string | undefined;
    expiresAt?: Date | undefined;
    isTrial?: boolean;
}

export class TenantSubscriptionDto implements ITenantSubscriptionDto {
    subscriptionId?: number;
    tenantId?: number;
    planId?: number;
    planName?: string | undefined;
    startDate?: Date;
    endDate?: Date;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;

    constructor(data?: ITenantSubscriptionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.subscriptionId = _data["subscriptionId"];
            this.tenantId = _data["tenantId"];
            this.planId = _data["planId"];
            this.planName = _data["planName"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : undefined as any;
            this.isActive = _data["isActive"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
        }
    }

    static fromJS(data: any): TenantSubscriptionDto {
        data = typeof data === 'object' ? data : {};
        let result = new TenantSubscriptionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["subscriptionId"] = this.subscriptionId;
        data["tenantId"] = this.tenantId;
        data["planId"] = this.planId;
        data["planName"] = this.planName;
        data["startDate"] = this.startDate ? formatDate(this.startDate) : undefined as any;
        data["endDate"] = this.endDate ? formatDate(this.endDate) : undefined as any;
        data["isActive"] = this.isActive;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        return data;
    }
}

export interface ITenantSubscriptionDto {
    subscriptionId?: number;
    tenantId?: number;
    planId?: number;
    planName?: string | undefined;
    startDate?: Date;
    endDate?: Date;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}

export class UpdateSubscriptionFeatureRequest implements IUpdateSubscriptionFeatureRequest {
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean | undefined;

    constructor(data?: IUpdateSubscriptionFeatureRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.category = _data["category"];
            this.dataType = _data["dataType"];
            this.defaultValue = _data["defaultValue"];
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): UpdateSubscriptionFeatureRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSubscriptionFeatureRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["category"] = this.category;
        data["dataType"] = this.dataType;
        data["defaultValue"] = this.defaultValue;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IUpdateSubscriptionFeatureRequest {
    name?: string | undefined;
    description?: string | undefined;
    category?: string | undefined;
    dataType?: string | undefined;
    defaultValue?: string | undefined;
    isActive?: boolean | undefined;
}

export class UpdateSubscriptionPlanRequest implements IUpdateSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: IUpdateSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUpdateSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;
}

export class UpdateTenantSubscriptionRequest implements IUpdateTenantSubscriptionRequest {
    endDate?: Date | undefined;
    isActive?: boolean | undefined;

    constructor(data?: IUpdateTenantSubscriptionRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.endDate = _data["endDate"] ? new Date(_data["endDate"].toString()) : undefined as any;
            this.isActive = _data["isActive"];
        }
    }

    static fromJS(data: any): UpdateTenantSubscriptionRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateTenantSubscriptionRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["endDate"] = this.endDate ? formatDate(this.endDate) : undefined as any;
        data["isActive"] = this.isActive;
        return data;
    }
}

export interface IUpdateTenantSubscriptionRequest {
    endDate?: Date | undefined;
    isActive?: boolean | undefined;
}

export class UpdateUserSubscriptionPlanRequest implements IUpdateUserSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;

    constructor(data?: IUpdateUserSubscriptionPlanRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(FeatureValueRequest.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UpdateUserSubscriptionPlanRequest {
        data = typeof data === 'object' ? data : {};
        let result = new UpdateUserSubscriptionPlanRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUpdateUserSubscriptionPlanRequest {
    name?: string | undefined;
    description?: string | undefined;
    price?: number | undefined;
    durationMonths?: number | undefined;
    currency?: string | undefined;
    displayOrder?: number | undefined;
    isPopular?: boolean | undefined;
    isActive?: boolean | undefined;
    features?: FeatureValueRequest[] | undefined;
}

export class UserSubscriptionPlanDto implements IUserSubscriptionPlanDto {
    id?: number;
    tenantId?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;

    constructor(data?: IUserSubscriptionPlanDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.tenantId = _data["tenantId"];
            this.code = _data["code"];
            this.name = _data["name"];
            this.description = _data["description"];
            this.price = _data["price"];
            this.durationMonths = _data["durationMonths"];
            this.currency = _data["currency"];
            this.displayOrder = _data["displayOrder"];
            this.isPopular = _data["isPopular"];
            this.isActive = _data["isActive"];
            this.createdAt = _data["createdAt"] ? new Date(_data["createdAt"].toString()) : undefined as any;
            this.updatedAt = _data["updatedAt"] ? new Date(_data["updatedAt"].toString()) : undefined as any;
            if (Array.isArray(_data["features"])) {
                this.features = [] as any;
                for (let item of _data["features"])
                    this.features!.push(PlanFeatureValueDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserSubscriptionPlanDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserSubscriptionPlanDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["tenantId"] = this.tenantId;
        data["code"] = this.code;
        data["name"] = this.name;
        data["description"] = this.description;
        data["price"] = this.price;
        data["durationMonths"] = this.durationMonths;
        data["currency"] = this.currency;
        data["displayOrder"] = this.displayOrder;
        data["isPopular"] = this.isPopular;
        data["isActive"] = this.isActive;
        data["createdAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["updatedAt"] = this.updatedAt ? this.updatedAt.toISOString() : undefined as any;
        if (Array.isArray(this.features)) {
            data["features"] = [];
            for (let item of this.features)
                data["features"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUserSubscriptionPlanDto {
    id?: number;
    tenantId?: number;
    code?: string | undefined;
    name?: string | undefined;
    description?: string | undefined;
    price?: number;
    durationMonths?: number;
    currency?: string | undefined;
    displayOrder?: number;
    isPopular?: boolean;
    isActive?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
    features?: PlanFeatureValueDto[] | undefined;
}

export class UserSubscriptionStatusDto implements IUserSubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    isTrial?: boolean;
    planName?: string | undefined;
    startDate?: Date | undefined;
    expiresAt?: Date | undefined;
    effectiveFeatures?: PlanFeatureValueDto[] | undefined;

    constructor(data?: IUserSubscriptionStatusDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.isActive = _data["isActive"];
            this.isExpired = _data["isExpired"];
            this.isTrial = _data["isTrial"];
            this.planName = _data["planName"];
            this.startDate = _data["startDate"] ? new Date(_data["startDate"].toString()) : undefined as any;
            this.expiresAt = _data["expiresAt"] ? new Date(_data["expiresAt"].toString()) : undefined as any;
            if (Array.isArray(_data["effectiveFeatures"])) {
                this.effectiveFeatures = [] as any;
                for (let item of _data["effectiveFeatures"])
                    this.effectiveFeatures!.push(PlanFeatureValueDto.fromJS(item));
            }
        }
    }

    static fromJS(data: any): UserSubscriptionStatusDto {
        data = typeof data === 'object' ? data : {};
        let result = new UserSubscriptionStatusDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["isActive"] = this.isActive;
        data["isExpired"] = this.isExpired;
        data["isTrial"] = this.isTrial;
        data["planName"] = this.planName;
        data["startDate"] = this.startDate ? this.startDate.toISOString() : undefined as any;
        data["expiresAt"] = this.expiresAt ? this.expiresAt.toISOString() : undefined as any;
        if (Array.isArray(this.effectiveFeatures)) {
            data["effectiveFeatures"] = [];
            for (let item of this.effectiveFeatures)
                data["effectiveFeatures"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

export interface IUserSubscriptionStatusDto {
    isActive?: boolean;
    isExpired?: boolean;
    isTrial?: boolean;
    planName?: string | undefined;
    startDate?: Date | undefined;
    expiresAt?: Date | undefined;
    effectiveFeatures?: PlanFeatureValueDto[] | undefined;
}

function formatDate(d: Date) {
    return d.getFullYear() + '-' + 
        (d.getMonth() < 9 ? ('0' + (d.getMonth()+1)) : (d.getMonth()+1)) + '-' +
        (d.getDate() < 10 ? ('0' + d.getDate()) : d.getDate());
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}