/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { OAuth2Token } from './o-auth2-token';


export interface OAuth2Provider { 
    providerId?: number;
    tenantId?: number;
    providerName?: string | null;
    clientId?: string | null;
    clientSecret?: string | null;
    authorizationUrl?: string | null;
    tokenUrl?: string | null;
    userInfoUrl?: string | null;
    redirectUrl?: string | null;
    scope?: string | null;
    isEnabled?: boolean;
    createdAt?: string;
    updatedAt?: string;
    tenant?: Tenant;
    oAuth2Tokens?: Array<OAuth2Token> | null;
}

