/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface RefreshToken { 
    refreshTokenId?: number;
    userId?: number;
    tokenHash?: string | null;
    expiresAt?: string;
    isRevoked?: boolean;
    revokedAt?: string | null;
    ipAddress?: string | null;
    userAgent?: string | null;
    deviceId?: string | null;
    createdAt?: string;
    user?: User;
    readonly isExpired?: boolean;
    readonly isActive?: boolean;
}

