/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';
import { UserRole } from './user-role';


export interface Role { 
    roleId?: number;
    roleName?: string | null;
    createdAt?: string;
    tenantId?: number;
    tenant?: Tenant;
    userRoles?: Array<UserRole> | null;
}

