/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface TenantUserPlan { 
    tenantUserPlanId?: number;
    tenantId?: number;
    planName?: string | null;
    price?: number;
    durationMonths?: number;
    featuresJson?: string | null;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
    tenant?: Tenant;
}

