/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tenant } from './tenant';


export interface TenantFeature { 
    featureId?: number;
    featureName?: string | null;
    createdAt?: string;
    isEnabled?: boolean;
    tenantId?: number;
    tenant?: Tenant;
    updatedAt?: string;
}

