/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserSession { 
    sessionId?: number;
    userId?: number;
    sessionHash?: string | null;
    expiresAt?: string;
    isActive?: boolean;
    deviceId?: string | null;
    deviceInfo?: string | null;
    ipAddress?: string | null;
    userAgent?: string | null;
    lastActivityAt?: string;
    createdAt?: string;
    terminatedAt?: string | null;
    rotatedFromSessionId?: number | null;
    revokedReason?: string | null;
    tenantId?: number;
    rowVersion?: string | null;
    lastActivity?: string;
    logoutAt?: string | null;
    user?: User;
}

