/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { User } from './user';


export interface UserRole { 
    userId?: number;
    roleId?: number;
    tenantId?: number;
    assignedAt?: string;
    user?: User;
    role?: Role;
}

