/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';


export interface UserSubscription { 
    id?: number;
    createdAt?: string;
    updatedAt?: string | null;
    isDeleted?: boolean;
    createdBy?: number | null;
    updatedBy?: number | null;
    subscriptionId?: number;
    userId?: number;
    tenantId?: number;
    tenantUserPlanId?: number;
    startDate?: string;
    endDate?: string;
    isActive?: boolean;
    user?: User;
}

