/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSubscription } from './user-subscription';
import { RefreshToken } from './refresh-token';
import { Tenant } from './tenant';
import { LoginHistory } from './login-history';
import { UserRole } from './user-role';
import { UserSettings } from './user-settings';
import { UserSession } from './user-session';
import { OAuth2Token } from './o-auth2-token';
import { AuthenticationMethod } from './authentication-method';
import { Notification } from './notification';
import { UserPermission } from './user-permission';


export interface User { 
    id?: number;
    email?: string | null;
    createdAt?: string;
    isActive?: boolean;
    isSuperAdmin?: boolean;
    tenantId?: number;
    passwordHash?: string | null;
    updatedAt?: string;
    tenant?: Tenant;
    refreshTokens?: Array<RefreshToken> | null;
    authenticationMethods?: Array<AuthenticationMethod> | null;
    oAuth2Tokens?: Array<OAuth2Token> | null;
    userRoles?: Array<UserRole> | null;
    userPermissions?: Array<UserPermission> | null;
    userSessions?: Array<UserSession> | null;
    loginHistories?: Array<LoginHistory> | null;
    notifications?: Array<Notification> | null;
    userSettings?: Array<UserSettings> | null;
    userSubscriptions?: Array<UserSubscription> | null;
    isDeleted?: boolean;
}

