/**
 * Matrimonial SaaS - Identity Service API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { User } from './user';
import { Permission } from './permission';


export interface UserPermission { 
    userPermissionId?: number;
    userId?: number;
    permissionId?: number;
    tenantId?: number;
    grantedBy?: number | null;
    grantedAt?: string;
    expiresAt?: string | null;
    assignedAt?: string;
    user?: User;
    permission?: Permission;
}

